# Generated by Django 4.2.9 on 2024-03-04 09:07

import common.library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providergallery",
            name="media",
            field=models.FileField(
                upload_to=common.library._get_file_path, verbose_name="media"
            ),
        ),
    ]
