# Generated by Django 4.2.9 on 2024-03-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_providergallery_media"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
