# Generated by Django 4.2.9 on 2024-03-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="holidays",
        ),
    ]
