# Generated by Django 4.2.9 on 2024-03-04 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_serviceprovider_holidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="holidays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
