# Generated by Django 4.2.9 on 2024-03-14 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="customer",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="duration",
            field=models.DurationField(default="00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="status",
            field=models.IntegerField(
                choices=[(101, "Pending"), (111, "Attended"), (121, "Canceled")],
                default=101,
                verbose_name="Time Slot Status",
            ),
        ),
    ]
