# Generated by Django 4.2.9 on 2024-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_timeslot_customer_timeslot_duration_timeslot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
